version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: carebridge
    ports: ["5432:5432"]
    volumes: [dbdata:/var/lib/postgresql/data]

  api:
    build: ./apps/api
    env_file: .env
    depends_on: [db]
    ports: ["8000:8000"]
    command: uvicorn apps.api.main:app --host 0.0.0.0 --port 8000 --reload

  web:
    build: ./apps/web
    environment:
      - VITE_API_URL=http://localhost:8000
    ports: ["5173:5173"]

volumes:
  dbdata:
